<script>
	export let filteredChords;
	
	import songs from './songs.json';

	import Song from '$lib/Song.svelte';

	// const chordList = filteredChords.map((chord) => chord.value);
	
	// console.log("chords ", chordList)
	
</script>

<div class="glass">
	<form action="">
		<input type="search" id="song-search" name="song-search" placeholder="Search songs..." />
	</form>
	
</div>


<div>
	{#each songs as {name, chords}}
		<Song title={name} artist={chords}/>
	{/each}

</div>


<style>

	form {
		width: 100%;
	}

	input {
		width: 100%;
		padding: 1rem;
		border-radius: 4px;
		border: 0;
	}

	.glass {
		padding: 4rem 2rem;
		margin-bottom: 1rem;

		backdrop-filter: blur(16px) saturate(120%);
		-webkit-backdrop-filter: blur(16px) saturate(120%);
		background-color: rgba(255, 255, 255, 0.2);
		border-radius: 12px;
		border: 1px solid rgba(209, 213, 219, 0.3);
	}
	/* Generated by https://generator.ui.glass/ */
</style>
