<script>
	import { onMount } from 'svelte';

	import { persisted } from 'svelte-persisted-store';

	import { dndzone, overrideItemIdKeyNameBeforeInitialisingDndZones } from 'svelte-dnd-action';
	import Svelecte from 'svelecte';
	import Papa from 'papaparse';

	import '../app.css';

	import SearchResults from '$lib/SearchResults.svelte';
	import options from '$lib/chords.js';

	overrideItemIdKeyNameBeforeInitialisingDndZones('value');

	let chordSelection = [null];
	let genreSelection = [null];
	export let storedChords = persisted('storedChords', chordSelection);
	export let storedGenres = persisted('storedGenres', genreSelection);

	const genres = [
		'rock',
		'alternative',
		'pop',
		'punk',
		'soul',
		'reggae',
		'electronica',
		'dance',
		'metal',
		'classic rock',
		'country',
		'britpop'
	];

	onMount(() => {
		genreSelection = $storedGenres;
		chordSelection = $storedChords;
	});

	function storeChords() {
		chordSelection = $storedChords;
	}

	function storeGenres(event) {
		let isInArray = genreSelection.includes(event.target.value);

		if (event.target.checked == true && !isInArray) {
			genreSelection = [...genreSelection, event.target.value];
		}

		if (event.target.checked == false && isInArray) {
			genreSelection = genreSelection.filter(function (value) {
				return value !== event.target.value;
			});
		}

		return;
	}

	function saveForm(event) {
		event.preventDefault();

		let length =
			chordSelection.length > genreSelection.length ? chordSelection.length : genreSelection.length;

		const data = [];

		// Add headers manually
		data.push(['chords, genres']);

		let row = [];
		for (let i = 0; i < length; i++) {
			row = ['', ''];
			row[0] = chordSelection[i] !== undefined ? JSON.stringify(chordSelection[i]) : '';
			row[1] = genreSelection[i] !== undefined ? genreSelection[i] : '';
			data.push(row);
		}

		const csv = Papa.unparse(data, {
			columns: ['chords, genres'],
			quoteChar: "'"
		});

		const blob = new Blob([csv], { type: 'text/csv' });
		const url = window.URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.setAttribute('href', url);
		a.setAttribute('download', 'stringQuerySettings.csv');
		a.click();
	}

	function clickBrowse() {
		let fileInput = document.getElementById('importFile');
		fileInput.click();
	}

	function loadForm(event) {
		let data;

		Papa.parse(event.target.files[0], {
			quoteChar: "'",
			complete: function (result) {
				data = result.data;

				if (data[0][0] === 'chords, genres') {
					document.getElementById('warning').style.display = 'none';
					parseData(data);
				} else {
					document.getElementById('warning').style.display = 'block';
				}
			}
		});
	}

	function parseData(data) {
		chordSelection = [];
		genreSelection = [];
		data.shift();

		data.forEach((item) => {
			if (item[0] !== '') {
				chordSelection.push(JSON.parse(item[0]));
			}

			if (item[1] !== '') {
				genreSelection.push(item[1]);
			}
		});

		$storedChords = chordSelection;
		$storedGenres = genreSelection;
	}
</script>

<main>
	<h1>String Query</h1>

	<div class="glass">
		<form action="">
			<div id="loadButtons">
				<button id="importButton" on:click={clickBrowse}>Import</button>
				<input type="file" id="importFile" on:change={loadForm} accept=".csv" />
				<p id="warning">File cannot be loaded. Please choose another.</p>
				<button id="exportButton" type="submit" on:click={saveForm}>Export</button>
			</div>

			<label for="chords">Add chords</label>

			<Svelecte
				{options}
				name="chords"
				bind:value={$storedChords}
				on:change={storeChords}
				multiple
				{dndzone}
				placeholder="Add chords..."
			/>

			<fieldset>
				<legend>Genres</legend>

				{#each genres as genre}
					<div>
						<label for={genre}>{genre.charAt(0).toUpperCase() + genre.slice(1)}</label>
						<input
							type="checkbox"
							bind:group={$storedGenres}
							on:change={storeGenres}
							id={genre}
							name="genres"
							value={genre}
						/>
					</div>
				{/each}
			</fieldset>
		</form>
	</div>

	{#key chordSelection || genreSelection}
		<SearchResults filteredChords={chordSelection} filteredGenres={genreSelection} />
	{/key}
</main>

<style>
	main {
		width: 100%;
		max-width: 800px;
		margin: 0 auto;
	}

	h1 {
		text-align: center;
		font-size: 4rem;
	}

	h1,
	label,
	legend {
		color: var(--color-text-light);
	}

	fieldset {
		margin-top: 1rem;
	}

	#loadButtons {
		width: 100%;
		display: flex;
		justify-content: flex-end;
	}

	#warning {
		display: none;
	}

	#importFile {
		display: none;
	}

	/* Glassmorphism card effect */
	.glass {
		padding: 4rem 2rem;
		margin-bottom: 1rem;

		backdrop-filter: blur(16px) saturate(120%);
		-webkit-backdrop-filter: blur(16px) saturate(120%);
		background-color: rgba(255, 255, 255, 0.2);
		border-radius: 12px;
		border: 1px solid rgba(209, 213, 219, 0.3);
	}
	/* Generated by https://generator.ui.glass/ */

	button {
		color: var(--color-text-light);
		border-radius: 4px;
		background-color: var(--color-fg-dark);
		border: var(--color-fg-dark);
		padding: 0.4rem 0.8rem;
		margin-bottom: 1rem;
		margin-right: 1rem;
	}

	button:hover {
		border-color: var(--color-fg-light);
		cursor: pointer;
	}
</style>
